"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path
import environ  # Importação para ler as variáveis secretas do .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CONFIGURAÇÃO DO LEITOR .ENV GERAL (Busca em múltiplos locais para evitar caminhos errados)
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
environ.Env.read_env(os.path.join(BASE_DIR, 'portfolio', '.env'))
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v_i9hk=1$_m0#&iwdy%panxu=ex6%pywi1t#j17co60g0w60$^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Permite que o Codespaces aceda sem trancar a porta


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',     # Tem de vir obrigatoriamente antes do staticfiles
    'cloudinary',             # Motor do Cloudinary ativo
    'django.contrib.staticfiles',
    'portfolio',
    'markdownify',
    'accounts',
    'artigos',
]

# --- CONFIGURAÇÕES DO MARKDOWNIFY ---
MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": [
            'a', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
            'strong', 'em', 'ul', 'ol', 'li', 'blockquote', 'code', 'br', 'hr', 'img'
        ]
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# Aponta dinamicamente para o Neon (PostgreSQL) configurado no teu .env
DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# Pasta no servidor onde os ficheiros vão ser guardados locais
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL pública para aceder aos ficheiros
MEDIA_URL = '/media/'

# Configuração do Cloudinary e ativação do novo sistema STORAGES para a nuvem
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# --- CONFIGURAÇÕES DE AUTENTICAÇÃO E EMAIL ---
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # login normal + admin
    'sesame.backends.ModelBackend',                # magic link
]

SESAME_MAX_AGE = 300 

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'