# Generated by Django 6.0.4 on 2026-04-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link_lusofona", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_curso", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ano_inicio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video_demo", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("link_repositorio", models.URLField()),
                ("destaque_interesse", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("nivel", models.CharField(max_length=50)),
                ("categoria", models.CharField(max_length=50)),
                (
                    "projetos",
                    models.ManyToManyField(
                        related_name="competencias", to="portfolio.projeto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_oficial", models.URLField()),
                ("nivel_interesse", models.IntegerField()),
                ("descricao_destaque", models.TextField()),
                (
                    "projetos",
                    models.ManyToManyField(
                        related_name="tecnologias", to="portfolio.projeto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.uc",
            ),
        ),
    ]
