# Generated by Django 6.0.4 on 2026-04-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacao",
            name="competencias",
            field=models.ManyToManyField(
                related_name="formacoes", to="portfolio.competencia"
            ),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfcs",
                to="portfolio.licenciatura",
            ),
        ),
    ]
